# Generated by Django 3.1 on 2021-11-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20211103_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
